config/routes.rb
OnlineShopping::Application.routes.draw do
  
  resources :orders, only: [:create, :destroy]
  get "orders/view_orders"
  get "product/index"
  post "carts/checkout"
  
  devise_for :customers

   root 'products#index'

     resources :products 
     resources :carts

  

end

app/models/cart.rb
class Cart < ActiveRecord::Base
	belongs_to :customer
	has_and_belongs_to_many :products
	before_destroy { products.clear }
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :validatable
  validates :name, presence: true
  validates :gender, presence: true
  validates :address, presence: true   
  has_many :orders    
  has_one :cart
end

app/models/order.rb
class Order < ActiveRecord::Base
	belongs_to :customer
	belongs_to :product
	validates :customer_id, presence: true
	validates :product_id, presence: true
end

app/models/product.rb
class Product < ActiveRecord::Base
	has_attached_file :image , :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/missing.jpeg"
	validates :name, presence: true, uniqueness: true
	validates :description, presence: true
	validates :price, presence: true
	has_many :orders
	has_and_belongs_to_many :carts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
      
      devise_parameter_sanitizer.for(:sign_up) do |u|
    	u.permit :name, :address, :password, :gender, :email, :Password_confirmation
     end
      
      devise_parameter_sanitizer.for(:account_update) do |u|
      u.permit :name, :address, :password, :gender, :email, :Password_confirmation, :current_password
     end
    
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def index
  end

  def new
  end

  def create
    cart_id = session[:cart_id]
    @cart = Cart.find(session[:cart_id])
    @product = Product.find(params[:id])
    @cart.products << @product
    
    # @cart_product = CartProducts.create(cart_id: cart_id, product_id: params[:id])
    
    redirect_to "/products"
  end

  def destroy
    cart_id = session[:cart_id]
    @cart = Cart.find(session[:cart_id])
    @product = Product.find(params[:id])
    @cart.products.delete(@product)
    redirect_to "/products"
    
  end

  def edit
  end

  def update
  end

  def checkout
    Cart.find(params[:id]).destroy
    redirect_to "/products"
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_customer!
  def view_orders
  	@orders=current_customer.orders
  end

  

  def create
  	@cart = Cart.find(params[:id])
    @current_order = []
    @cart.products.each do |product|

   	   @order = current_customer.orders.build(product_id: product.id)
       @order.save
       @current_order << @order

       end
       
       
    Cart.find(params[:id]).destroy
    
    render "checkout"
     
  end

  

  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	before_action :authenticate_customer!, only: [:new, :edit ]  
	def index
  	@products = Product.all
    
    if customer_signed_in?
      @cart = Cart.find_by customer_id: @current_customer.id
      
       if @cart.blank?
         @cart = @current_customer.build_cart
         @cart.save
       end
      session[:cart_id] = @cart.id
      @cart_products = @cart.products       
    end
  end

  def new
  	@product = Product.new
  end
  
  def create
    @product = Product.new(user_params)
    if @product.save
    	
    	 flash[:notice] = "Product added succesfully"
      redirect_to(root_url)
    else
      render 'new'
    end
  end
    
  def destroy
     Product.find(params[:id]).destroy
     flash[:notice] = "Product deleted."
     redirect_to(root_url)
  end

  def edit
    	@product = Product.find(params[:id])
  end
    
  def update
      @product = Product.find(params[:id])
      if @product.update_attributes(user_params)
        flash[:success] = "Product Updated"
       
        redirect_to(root_url)
      else
        render 'edit'
      end
  end

  private

 def user_params
      params.require(:product).permit(:name, :price, :description, :image)
                                   
    end

    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/views/cart/_cart.html.erb
Products in your cart

<% @carts.each do |product| %>
      <tr>
        <td><%= product.product_id %></td>

        <% end %>
        
       

app/views/cart/create.html.erb
<h1>Cart#create</h1>
<p>Find me in app/views/cart/create.html.erb</p>

app/views/cart/destroy.html.erb
<h1>Cart#destroy</h1>
<p>Find me in app/views/cart/destroy.html.erb</p>

app/views/cart/edit.html.erb
<h1>Cart#edit</h1>
<p>Find me in app/views/cart/edit.html.erb</p>

app/views/cart/index.html.erb
<h1>Cart#index</h1>
<p>Find me in app/views/cart/index.html.erb</p>

app/views/cart/new.html.erb
<h1>Cart#new</h1>
<p>Find me in app/views/cart/new.html.erb</p>

app/views/cart/update.html.erb
<h1>Cart#update</h1>
<p>Find me in app/views/cart/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]>    <html class="ie9" lang="en"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title>Shopping Portal<% content_for?(:title) ? yield(:title) : "Untitled" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
   <nav class="top-bar">
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to "Store", products_path %></a></h1>
    </li>
  </ul>
  <section class="top-bar-section">
    <ul class="right">
      <li class="divider"></li>
      <li><%= link_to "Browse Products", products_path %></li>
      <li class="divider"></li>
      <% if customer_signed_in? %>
      <% if not current_customer.admin? %>  
      <li><%= link_to "Previous Orders", orders_view_orders_path %></li>
      <li class="divider"></li>
      <% end %>
      
      
      <li><%= link_to "Profile", edit_customer_registration_path%></li>
      <li class="divider"></li>
      <li><%= link_to "Sign Out", destroy_customer_session_path, :method => :delete%></li>
      <% else %>
      <li>
      <%= link_to "Sign In", new_customer_session_path, :method => :get %></li>

       <% end %>
      
    </ul>
  </div>
</nav>

  
    
     <%= yield %>
  
    

    
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/orders/checkout.html.erb
<div class="row">
<div class="large-8 columns">
<div class="panel" id="homepanel">

<h1>Your Invoice</h1>
<table>
<tr><td>Order id</td>
<td>Product name</td>
<td>Product price</td></tr>
<% @current_order.each do |order| %>
<tr>
<td><%= order.id %></td>
<td><%= Product.find(order.product_id).name %></td>
<td><%= Product.find(order.product_id).price %></td>
 </tr>    
<% end %>

 </table>
<hr>

<%= link_to "Back to shopping", root_url, class: "button" %>

</div>
</div>

app/views/orders/view_orders.html.erb
<div class="row">
<div class="large-8 columns">
<h1>Previous orders</h1>

<table id="orders">
  <thead>
    <tr>
      <th>Order Id</th>
      <th>Product Name</th>
      <th>Amount(Rs.)</th>
      
    </tr>
  </thead>

  <tbody>
  
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.id %></td>
        <td><%= Product.find(order.product_id).name %></td>
        <td><%= Product.find(order.product_id).price %></td>
       
      </tr>
    <% end %>
    

  </tbody>
</table>
</div>
</div>

app/views/products/_cart.html.erb
<h3>Your cart!</h3>
<% cart_id = session[:cart_id] %>
You have <%= @cart_products.count %> product in your cart!
<br>
<br>
<% @cart_products.each do |product| %>

<%= product.name %>
 <td><%= link_to 'Remove', {:controller => "carts", :action => "destroy", :id => product.id}, method: :delete %></td>
 <br>
  <% end %>   
<hr>
<% if @cart_products.count > 0 %>
 <%= button_to 'Checkout',{:action => "create", :controller => "orders" , id: cart_id}, class: "small button" %>  
<% end %>       

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
     <%= f.label :name %><br>
     <%= f.text_field :name %>
  </div>
  <div>
   <%= f.label :price %><br>
   <%= f.text_field :price %>
  </div>
   <div>
    <%= f.label :description %><br>
   <%= f.text_area :description %>
  </div>
  <div>
     <%= f.label :image %><br>
    <%= f.file_field :image %>
   
  </div>
  <div>
    <%= f.submit "Done", class: "button" %>
  </div>
<% end %>

app/views/products/_listingproducts.html.erb
<h1>Listing products</h1>

<table id="products">
  <thead>
    <tr>
      <th>Name</th>
      <th>Image</th>
      <th>Price</th>
      <th>Description</th>
      <% if current_customer.admin? %>
      <th></th>
      <th></th>
      <% else %>
      <th></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= image_tag product.image.url(:thumb) %></td>
        <td><%= product.price %></td>
        <td><%= product.description %></td>
       
        
        <% if current_customer.admin? %>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% else %>

        <td><%= button_to 'Add to cart',:action => "create", :controller => "carts" , id: product.id%></td>
        <% end -%>
      </tr>
    <% end %>
  </tbody>
</table>
<hr>

app/views/products/edit.html.erb
<div class="row">
<div class="large-6 columns">
<h1>Editing product</h1>

<%= render 'form' %>


<%= link_to 'Back', products_path %>
</div>
</div>

app/views/products/index.html.erb
<% if customer_signed_in? %>
<div class="row">
  <div class="large-8 columns">
   <section>
    <%= render 'listingproducts' %>
   </section>
   <br>
  </div>
  <div class="large-1 columns">
  </div>
<div class="large-3 columns" id="userdetails">

<% if not current_customer.admin? %>
<%= render 'cart' %>



<br>
<h3>Your details</h3>

Name: <%= current_customer.name %><br></br>
Address: <%= current_customer.address %><hr>

Not correct! <%= link_to "edit here", edit_customer_registration_path, class: "small button" %>
<% end %>
</div>
  

</div>
<div class="row"></div>

<div class="row">

  <div class="small-11 small-centered columns">
    <% if current_customer.admin? %>
    <%= link_to 'Add New product', new_product_path,class: "button" %>
    <% end %>
  </div>

</div>


<% else %>
<div class="container">
<div class="row">
<div class="twelve columns">
<div class="panel" id="homepanel">

<h1 id="h1-home"> Welcome to shopping portal! </h1>

<%= link_to "Sign up", new_customer_registration_path, :method => :get,class: "button" %>

</div>
</div>
</div>
<% end %>

</div>

app/views/products/new.html.erb
<div class="row">
<div class="large-6 columns">
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>
</div>
</div>

app/views/shared/_shoppingcart.html.erb
<div class="panel callout">

Shopping cart

</div>